name: Build and Publish Docker Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          gradle-home-cache-cleanup: true

      - name: Run build with Gradle wrapper
        run: ./gradlew shadowJar

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: fusseltv
          password: dckr_pat_uxkzMELfS138kGYEyBYsPjxMF7c

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fusseltv/gym-webhook:latest